# Generated by Django 3.1.1 on 2021-01-20 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog_models',
            new_name='Project_blog',
        ),
    ]
