# Generated by Django 3.1.6 on 2021-02-16 05:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20210216_0342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='All_Blogs',
            new_name='AllBlogs',
        ),
    ]
